I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 737, in script
    menu solvemagic:
  File "game/script.rpy", line 746, in <module>
    "I learned something from another world that might help." if has_phil_philo:
NameError: name 'has_phil_philo' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 737, in script
    menu solvemagic:
  File "C:\Users\haapp\Desktop\Games\Ren'Py\renpy\ast.py", line 1619, in execute
    choice = renpy.exports.menu(choices, self.set, args, kwargs, item_arguments)
  File "C:\Users\haapp\Desktop\Games\Ren'Py\renpy\exports\menuexports.py", line 100, in menu
    condition = renpy.python.py_eval(condition)
  File "C:\Users\haapp\Desktop\Games\Ren'Py\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\haapp\Desktop\Games\Ren'Py\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 746, in <module>
    "I learned something from another world that might help." if has_phil_philo:
NameError: name 'has_phil_philo' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.2.24090902
BubbleWitchMultiverseGame 1.0
Sun Jan 26 13:48:30 2025
